test.new_world("demo", "2019", "core:default")
assert(world.is_open())
assert(world.get_generator() == "core:default")
test.sleep(1)
assert(world.get_total_time() > 0.0)
print(world.get_total_time())
test.close_world(true)
assert(not world.is_open())
