devtools.console="key:grave-accent"
chunks.reload="key:f5"
movement.forward="key:w"
movement.back="key:s"
movement.left="key:a"
movement.right="key:d"
movement.jump="key:space"
movement.sprint="key:left-ctrl"
movement.crouch="key:left-shift"
movement.cheat="key:r"
camera.zoom="key:c"
camera.mode="key:f4"
player.noclip="key:n"
player.flight="key:f"
player.attack="mouse:left"
player.destroy="mouse:left"
player.build="mouse:right"
player.pick="mouse:middle"
player.drop="key:q"
player.fast_interaction="key:x"
hud.inventory="key:tab"
hud.chat="key:t"
