name: Test

on:
  push:
    branches: [ "main", "release-**", "new-workflow"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:

    strategy:
      matrix:
        include:
          - os: windows-latest
            compiler: clang

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: msys2/setup-msys2@v2
        with:
            msystem: clang64
            install: mingw-w64-clang-x86_64-cmake
      - name: Configure and build project with CMake and vcpkg
        shell: msys2 {0}
        run: |
           mkdir build
           cd build
           mingw-w64-clang-x86_64-cmake -DCMAKE_BUILD_TYPE=Release -DVOXELENGINE_BUILD_WINDOWS_VCPKG=ON -DVOXELENGINE_BUILD_TESTS=ON ..
