name: Test

on:
  push:
    branches: [ "main", "release-**", "new-workflow"]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:

    strategy:
      matrix:
        include:
          - os: windows-latest
            compiler: clang

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: msys2/setup-msys2@v2
        with:
            msystem: clang64
            install: mingw-w64-clang-x86_64-cmake
      - run: tree C:\msys\mingw64\
      - name: Add clang to PATH
        shell: bash
        run: echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
    #   - name: Configure and build project with CMake and vcpkg
    #     shell: bash
    #     run: |
    #        mkdir build
    #        cd build
    #        mingw-w64-cmake -DCMAKE_BUILD_TYPE=Release -DVOXELENGINE_BUILD_WINDOWS_VCPKG=ON -DVOXELENGINE_BUILD_TESTS=ON ..
